blank_issues_enabled: false
contact_links:
  - name: Question or general feedback
    url: https://github.com/royklo/PPPC-Builder-v2/discussions
    about: For questions about how to use PPPC Builder or general feedback, please open a discussion.
